pipeline
{

agent {
  label 'DevServer'
}
  environment {
  name = "kavya"
}

tools {
  maven 'mymaven'
}

stages{

    stage('build')
    {
        steps {
            sh 'mvn clean package'
            echo "hello $name"
        }

        post {
        success {
            archiveArtifacts artifacts: '**/target/*.jar'
                 }
            }

    }

   

    
}

}
