pipeline
{

agent {
  label 'DevServer'
}
  environment {
  name = "kavya"
}
  
parameters {
  string defaultValue: 'mamatha', name: 'user'
}
  
tools {
  maven 'mymaven'
}

stages{

    stage('build')
    {
        steps {
            sh 'mvn clean package'
          echo "hello $name ${params.user}"
            
        }

        post {
        success {
            archiveArtifacts artifacts: '**/target/*.jar'
                 }
            }

    }

   

    
}

}
